/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as MisionRouteImport } from './routes/mision'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as FilosofiaRouteImport } from './routes/filosofia'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionRoute = MisionRouteImport.update({
  id: '/mision',
  path: '/mision',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const FilosofiaRoute = FilosofiaRouteImport.update({
  id: '/filosofia',
  path: '/filosofia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/filosofia': typeof FilosofiaRoute
  '/gracias': typeof GraciasRoute
  '/mision': typeof MisionRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/filosofia': typeof FilosofiaRoute
  '/gracias': typeof GraciasRoute
  '/mision': typeof MisionRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/filosofia': typeof FilosofiaRoute
  '/gracias': typeof GraciasRoute
  '/mision': typeof MisionRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/filosofia'
    | '/gracias'
    | '/mision'
    | '/quienes-somos'
    | '/trabaja-con-nosotros'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/filosofia'
    | '/gracias'
    | '/mision'
    | '/quienes-somos'
    | '/trabaja-con-nosotros'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/filosofia'
    | '/gracias'
    | '/mision'
    | '/quienes-somos'
    | '/trabaja-con-nosotros'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoberturaRoute: typeof CoberturaRoute
  ContactoRoute: typeof ContactoRoute
  FilosofiaRoute: typeof FilosofiaRoute
  GraciasRoute: typeof GraciasRoute
  MisionRoute: typeof MisionRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision': {
      id: '/mision'
      path: '/mision'
      fullPath: '/mision'
      preLoaderRoute: typeof MisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filosofia': {
      id: '/filosofia'
      path: '/filosofia'
      fullPath: '/filosofia'
      preLoaderRoute: typeof FilosofiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoberturaRoute: CoberturaRoute,
  ContactoRoute: ContactoRoute,
  FilosofiaRoute: FilosofiaRoute,
  GraciasRoute: GraciasRoute,
  MisionRoute: MisionRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
